#!/bin/bash
#
# Ablation Studies Execution Script
# Generated by phase3_ablation_studies.py
#
# Usage: bash scripts/run_ablations.sh
#

set -e  # Exit on error

echo '======================================================================'
echo 'TAC-LANOBERT V2 - ABLATION STUDIES'
echo '======================================================================'
echo

TOTAL_EXPERIMENTS=35
CURRENT=0

# Function to run single experiment
run_experiment() {
    CONFIG=$1
    CURRENT=$((CURRENT + 1))
    
    echo
    echo '----------------------------------------------------------------------'
    echo "Experiment $CURRENT/$TOTAL_EXPERIMENTS: $CONFIG"
    echo '----------------------------------------------------------------------'
    
    python3 experiments/run_tac_v2.py --config "$CONFIG"
    
    if [ $? -eq 0 ]; then
        echo "✅ Experiment $CURRENT completed successfully"
    else
        echo "❌ Experiment $CURRENT failed"
        exit 1
    fi
}

# Run all experiments

run_experiment 'configs/ablations/e1_alpha_0.00.yaml'
run_experiment 'configs/ablations/e1_alpha_0.10.yaml'
run_experiment 'configs/ablations/e1_alpha_0.30.yaml'
run_experiment 'configs/ablations/e1_alpha_0.50.yaml'
run_experiment 'configs/ablations/e1_alpha_0.70.yaml'
run_experiment 'configs/ablations/e1_alpha_0.90.yaml'
run_experiment 'configs/ablations/e1_alpha_0.95.yaml'
run_experiment 'configs/ablations/e1_alpha_1.00.yaml'
run_experiment 'configs/ablations/e2_memory_32.yaml'
run_experiment 'configs/ablations/e2_memory_64.yaml'
run_experiment 'configs/ablations/e2_memory_128.yaml'
run_experiment 'configs/ablations/e2_memory_256.yaml'
run_experiment 'configs/ablations/e2_memory_512.yaml'
run_experiment 'configs/ablations/e3_pca_32.yaml'
run_experiment 'configs/ablations/e3_pca_64.yaml'
run_experiment 'configs/ablations/e3_pca_128.yaml'
run_experiment 'configs/ablations/e3_pca_256.yaml'
run_experiment 'configs/ablations/e3_pca_none.yaml'
run_experiment 'configs/ablations/e4_loss_standard.yaml'
run_experiment 'configs/ablations/e4_loss_penalty.yaml'
run_experiment 'configs/ablations/e4_loss_smoothness.yaml'
run_experiment 'configs/ablations/e4_loss_ranking.yaml'
run_experiment 'configs/ablations/e4_loss_contrastive.yaml'
run_experiment 'configs/ablations/e5_aug_none.yaml'
run_experiment 'configs/ablations/e5_aug_low.yaml'
run_experiment 'configs/ablations/e5_aug_medium.yaml'
run_experiment 'configs/ablations/e5_aug_high.yaml'
run_experiment 'configs/ablations/e6_temporal_none.yaml'
run_experiment 'configs/ablations/e6_temporal_time_only.yaml'
run_experiment 'configs/ablations/e6_temporal_rate_only.yaml'
run_experiment 'configs/ablations/e6_temporal_delta_only.yaml'
run_experiment 'configs/ablations/e6_temporal_all.yaml'
run_experiment 'configs/ablations/e7_dataset_bgl.yaml'
run_experiment 'configs/ablations/e7_dataset_hdfs.yaml'
run_experiment 'configs/ablations/e7_dataset_thunderbird.yaml'

echo
echo '======================================================================'
echo '✅ ALL ABLATION STUDIES COMPLETE'
echo '======================================================================'
echo
echo 'Results saved to: outputs/ablations/'
echo
echo 'Next steps:'
echo '  1. Analyze results: python experiments/analyze_ablations.py'
echo '  2. Generate report: python experiments/report_ablations.py'
echo '  3. Select best configuration'
